### ISSUE TITLE
error running node pdf2svg.js

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#8902]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: node
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 23cbe294d578085c295e700963c092816b5bf7e3
- Is an extension: no

Steps to reproduce the problem:
1.  cd examples/node
2. node pdf2svg.js

What is the expected behavior? (add screenshot)
convert pdf to svg

What went wrong? (add screenshot)
```
Error: TypeError: svg.setAttribute is not a function
```

**Comment by timvandermeij** [comment]
Do you have a PDF file for which this happens?

**Comment by yurydelendik** [comment]
@timvandermeij I think our node stub is not having setAttribute method https://github.com/mozilla/pdf.js/blob/master/examples/node/domstubs.js#L81

**Comment by timvandermeij** [comment]
You're right. This is a Node.js-specific regression from PR #8691 from three days ago. I'll check if I can fix this.
