### ISSUE TITLE
SVG: TypeError: bytes.subarray is not a function

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#14952]
This pdf:  [page-7.pdf](https://github.com/mozilla/pdf.js/files/8753435/page-7.pdf)

Command line:
````
git clone https://github.com/mozilla/pdf.js.git
npm install
node_modules/.bin/gulp generic-legacy
# examples/node/pdf2svg.js:
#      const pdfjsLib = require("../../build/generic-legacy/build/pdf.js");
node examples/node/pdf2svg.js /tmp/page-7.pdf
````

Console:
````
# Document Loaded
Number of Pages: 1

# Page 1
Size: 612x792

Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Error: TypeError: bytes.subarray is not a function
# End of Document
````

**Comment by Snuffleupagus** [comment]
Given that the SVG back-end is *not* officially supported, note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends, it's not clear (at least to me) that it makes sense to try and fix this.

**Comment by doublex** [comment]
The SVG backend works really great! (beside some tiny issues)

**Comment by pleswi** [comment]
I have same problem. I use svg back-end more than 2 years and this is first problem. Attached PDF is scanned document
[osivo-KWS-gmo-free.pdf](https://github.com/mozilla/pdf.js/files/8754597/osivo-KWS-gmo-free.pdf)
.

**Comment by doublex** [comment]
@pleswi 
`2.13.216` works for me

**Comment by pleswi** [comment]
I confirm, it works with `2.13.216`

**Comment by danopia** [comment]
I can similarly confirm with my own PDF file that `2.14.305` throws this error when rendering SVG while `2.13.216` seems to work.

I did some light debugging and found that the literal string `"mask_p0_2"` was making its way into the part of the code which expects a `Uint8ClampedArray`.

**Comment by doublex** [comment]
@danopia 
Did you find a solution?

**Comment by danopia** [comment]
My solution is using `2.13.216` 😄 

Some clever use of `git bisect` should be able to find the exact commit that introduced the regression. I only came across `pdf.js` today. so I don't know much more than what's in this thread yet.

**Comment by doublex** [comment]
According to `git bisect`:
https://github.com/mozilla/pdf.js/commit/040fcae5ab08d1116ccfdd0cee45c1ffefff6c0e

**Comment by Snuffleupagus** [comment]
*Following up on https://github.com/mozilla/pdf.js/issues/14952#issuecomment-1152397525:* If those affected by this bug are willing to compensate me for my time/knowledge, I could (pretty easily) provide a patch for this.

---

Please also note that since this issue was opened the SVG back-end is no longer just unmaintained/unsupported, but it's now also been officially deprecated; see https://github.com/mozilla/pdf.js/blob/7b24931f673d68803d9dac4567ba0462ec89a835/src/display/svg.js#L468-L472

We're pretty close to the next *major* PDF.js release (from `3`-branch) and after that the SVG back-end will in all likelihood receive no additional work/fixes.
