### PR TITLE
Fix a typo causing a TypeError when attempting to call pdfHistory_clearHistoryState (issue 6121)

### LINKED ISSUE #6121: PDFJS throwing PDFHistory.clearHistoryState is not a function error
Sir,
while changing <b>showPreviousViewOnLoad: true,</b> to <b>showPreviousViewOnLoad: false,</b>
under the file <b>default_prefereneces.js</b> in pdf.js provided by mozilla, it is throwing following error in viewer.html
<b><em>Uncaught (in promise) TypeError: PDFHistory.clearHistoryState is not a function</em></b>.
Is there any configuration required to make it work.

Thank you!

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6121.

Note: This "regressed" in PR #5823.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Since the patch is trivial, and given that it fixes a recent regression, I'm going to merge it with r=me.
