### PR TITLE
[api-minor] Make `isOffscreenCanvasSupported` configurable via the API (issue 14952)

### LINKED ISSUE #14952: SVG: TypeError: bytes.subarray is not a function
This pdf:  [page-7.pdf](https://github.com/mozilla/pdf.js/files/8753435/page-7.pdf)

Command line:
````
git clone https://github.com/mozilla/pdf.js.git
npm install
node_modules/.bin/gulp generic-legacy
# examples/node/pdf2svg.js:
#      const pdfjsLib = require("../../build/generic-legacy/build/pdf.js");
node examples/node/pdf2svg.js /tmp/page-7.pdf
````

Console:
````
# Document Loaded
Number of Pages: 1

# Page 1
Size: 612x792

Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented operator beginMarkedContentProps
Warning: Unimplemented operator endMarkedContent
Warning: Unimplemented graphic state operator SMask
Warning: Unimplemented graphic state operator BM
Error: TypeError: bytes.subarray is not a function
# End of Document
````

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch first of all makes `isOffscreenCanvasSupported` configurable, defaulting to `true` in browsers and `false` in Node.js environments, with a new `getDocument` parameter. While you normally want to use this, in order to improve performance, it should still be possible for users to control it (similar to e.g. `isEvalSupported`).

The specific problem, as reported in issue #14952, is that the SVG back-end doesn't support the new ImageMask data-format that's introduced in PR #14754. In particular:
 - When the SVG back-end is used in Node.js environments, this patch will "just work" without the user needing to make any code changes.
 - If the SVG back-end is used in browsers, this patch will require that `isOffscreenCanvasSupported: false` is added to the `getDocument`-call.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM.
