### PR TITLE
[api-minor] Move Type3-glyph compilation to the worker-thread

### PR DESCRIPTION
**Pull request by Snuffleupagus**
After PR #19731 the format of compiled Type3-glyphs is now simple enough that the compilation can be moved to the worker-thread, without introducing any significant additional complexity.
This allows us to, ever so slightly, simplify the implementation in `src/display/canvas.js` since the Type3 operatorLists will now directly include standard path-rendering operators (using the format introduced in PR #19689).

As part of these changes we also stop caching Type3 image masks since: we've not come across any cases where that actually helps, they're usually fairly small, and it simplifies the code.

Note that one "negative" change introduced in this patch is that we'll now compile Type3-glyphs *eagerly*, whereas previously we'd only do that lazily upon their first use.
However, this doesn't seem to impact performance in any noticeable way since the compilation is fast enough (way below 1 ms/glyph in my testing) and Type3-fonts are also limited to just 256 glyphs. Also, many (or most?) Type3-fonts don't even use image masks and are thus not affected by these changes.

### CODE REVIEW

File: src/core/fonts_utils.js [hunk 1]
```diff
@@ -207,7 +207,177 @@ const getVerticalPresentationForm = getLookupTableFactory(t => {
...
+
+      if (!points[p]) {
+        --count;
+      }
+    } while (p0 !== p);
+    --i;
+  }
+
+  return [
+    OPS.fill,
```
Comment (calixteman) [inline src/core/fonts_utils.js:373]: It'll lead to call `canvas::fill` when we're just calling `ctx.fill` for now. 
Maybe we should add a method `fillPath` which only contains something like `ctx.fill`. Wdyt ?

File: src/core/evaluator.js [hunk 2]
```diff
@@ -616,25 +625,21 @@ class PartialEvaluator {
...
+          operatorList.addImageOps(OPS.constructPath, args, optionalContent);
+          return;
         }
+        warn("Cannot compile Type3 glyph.");
+
+        // If compilation failed, or was disabled, fallback to using an inline
+        // image mask; this case should be extremely rare.
+        operatorList.addImageOps(
+          OPS.paintImageMaskXObject,
+          [imgData],
```
Comment (calixteman) [inline src/core/evaluator.js:640]: I think we should create an ImageBitmap here.

File: src/core/fonts_utils.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/fonts_utils.js:373]: Sure, that obviously couldn't hurt (even is the effect is probably small).

File: src/core/evaluator.js (hunk 2 above)
Comment (Snuffleupagus) [reply src/core/evaluator.js:640]: While you're obviously technically correct, I'd say that it probably doesn't matter in practice since this is just a fallback code-path that we should "never" actually reach. (At least I've not seen any Type3-font where it happens.)

Hence I'd be inclined to leave this as-is for now, until we have any indication that this is actually a problem in practice.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
