### ISSUE TITLE
this.switchSidebarView is not a function

### ISSUE THREAD

**Issue by grassynoel** [mozilla/pdf.js#6377]
I upgraded from 1.1.144 to current and pre-release versions and receive an error while rendering a pdf. Is there anything I need to update on my end?

![image](https://cloud.githubusercontent.com/assets/1844517/9418458/04d7dea8-4809-11e5-8eed-0022bd4059fe.png)

Current code is pretty simple:
![image](https://cloud.githubusercontent.com/assets/1844517/9418478/3e89263e-4809-11e5-83cd-4109d61a5611.png)

**Comment by Snuffleupagus** [comment]
This was broken by PR #5971, and subsequently fixed by PR #6314.

The fix unfortunately landed too late in order to be included in the latest (pre-)release version, but it's present in the latest master. Please refer to [Getting the Code](https://github.com/mozilla/pdf.js#getting-the-code) and [Building PDF.js](https://github.com/mozilla/pdf.js#building-pdfjs) for information about obtaining/building the latest version of PDF.js.

Closing as answered, since this issue has already been resolved.

**Comment by grassynoel** [comment]
Will do, and thank for the quick response!
