### PR TITLE
Target ES2022 when building the TypeScript definitions (issue 17932)

### LINKED ISSUE #17932: Unable to build with 4.1.392:  error TS2304: Build:Cannot find name 'PromiseWithResolvers'
Attach (recommended) or Link to PDF file here:

Configuration:
- Visual Studio 2022 17.9.6
- .NET 8 Blazor
- PDF.js version: 4.1.392
- Node 20.12.2

Updated to the newest version and unable to build with Typescript. Something changed between 4.0 and 4.1.  Are there new dependencies needed?

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This should avoid the latest JS features appearing in the TypeScript definitions, and given the currently supported browsers/environments (in PDF.js) we shouldn't need to target an even older ES-version.

*Edit:* I again question the value of offering TypeScript definitions, since they cause nothing but maintenance overhead that is *unfortunately often not* shouldered by the actual TypeScript users.

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!
