### ISSUE TITLE
Old Version which compiles on OpenBSD6.6

### ISSUE THREAD

**Issue by feraldruid22** [mozilla/pdf.js#13231]
With the GIT version I get:

```
node make generic
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/pdf.js-master/make'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Node Version:
v10.16.3

System Version:
OpenBSD 6.6 GENERIC.MP#372 amd64

There is no native package for this. Can someone provide me with a version which compiles?

I need it for a 7 years old software:
https://gitlab.awesome-it.de/kolab/roundcube-plugins/tree/feature_caldav/plugins/pdfviewer

So I don't care the old had bugs I just want it to compile and work as soon as possible.

**Comment by Snuffleupagus** [comment]
> Node Version:
> v10.16.3

That Node.js version is now longer supported, as far as I can tell, and please note the PDF.js project cannot help with issues specifically related to Node.js usage.

> System Version:
> OpenBSD 6.6 GENERIC.MP#372 amd64

The PDF.js library is implemented in JavaScript, and primarily intended to run in browsers, hence the exact operating system used *shouldn't* matter too much in general.

> There is no native package for this.

What do you mean with "native package"?
The only builds that we provide, accept for what's shipping in Firefox, are the ones found at https://mozilla.github.io/pdf.js/getting_started/#download and https://github.com/mozilla/pdfjs-dist (or via https://www.npmjs.com/package/pdfjs-dist).

> Can someone provide me with a version which compiles?

Sorry, but we cannot provide users with *custom* builds; please keep in mind that this is first and foremost an open-source *bug tracker* rather than e.g. a support forum.

> I need it for a 7 years old software:
> https://gitlab.awesome-it.de/kolab/roundcube-plugins/tree/feature_caldav/plugins/pdfviewer

We know *nothing* about that project here, and consequently we unfortunately cannot provide help/support with using it.
