### ISSUE TITLE
[Bug]: Issue process.getBuildinModule not resolved (with NodeJS)

### ISSUE THREAD

**Issue by GreenFlag31** [mozilla/pdf.js#19194]
### Attach (recommended) or Link to PDF file

Environnement : 

- "pdfjs-dist": "^4.9.155"
- NodeJS v20.12.1

![image](https://github.com/user-attachments/assets/1183e306-f3b7-44bf-aa27-322d83427ed4)

Steps to reproduce : 
1. const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs'); (commonJS project)
2. this.pdfDocument = await pdf.getDocument(docParams).promise; (here I got the warnings, see picture)
3. const canvasAndContext = new NodeCanvasFactory().create(width, height); (here I'm using node canvas, but same result with napi-rs/canvas, or build-in method)
4. Have the issue

Btw, the build-in method is wrongly typed: 
![image](https://github.com/user-attachments/assets/62812844-fd2b-4120-b425-9a6075a56569)

It does not possess a `createCanvas` method, since this is a basic Object.

### Web browser and its version

N/A

### Operating system and its version

Windows 10

### PDF.js version

4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs'); (commonJS project)
2. this.pdfDocument = await pdf.getDocument(docParams).promise; (here I got the warnings, see picture)
3. const canvasAndContext = new NodeCanvasFactory().create(width, height); (here I'm using node canvas, but same result with napi-rs/canvas, or build-in method)
4. Have the issue

### What is the expected behavior?

It should transform the PDF to an image; was working with "pdfjs-dist": "4.7.76"

### What went wrong?

process.getBuildinModule is not a function

**Comment by Snuffleupagus** [comment]
> NodeJS v20.12.1

That version is too old, you need at least https://github.com/nodejs/node/releases/tag/v20.16.0

---

*For future reference:* Please provide error messages and code *as text*, rather than as images.

Please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by GreenFlag31** [comment]
Ok, working with node v22.

In the code, a check if (processbuildInModle in process) would have been possible, improving DX (and generating no ticket for that).

"first check the examples at https://github.com/mozilla/pdf.js#learning". Well, this is what I did, following the example [here](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.mjs). Hence the remark about wrongly typed `canvasFactory` method.

Is a typescript improvement planned ? If not, should / can I contribute to it ?
