### ISSUE TITLE
Unable to build with 4.1.392:  error TS2304: Build:Cannot find name 'PromiseWithResolvers'

### ISSUE THREAD

**Issue by Welchen** [mozilla/pdf.js#17932]
Attach (recommended) or Link to PDF file here:

Configuration:
- Visual Studio 2022 17.9.6
- .NET 8 Blazor
- PDF.js version: 4.1.392
- Node 20.12.2

Updated to the newest version and unable to build with Typescript. Something changed between 4.0 and 4.1.  Are there new dependencies needed?

**Comment by andreymyssak** [comment]
Small investigation from my side:
I've tested it on Node v20.11.1. The issue does not occur with pdfjs-dist v4.0.379. It only happens in v4.1.392, and I think this started after the changes made in https://github.com/mozilla/pdf.js/pull/17854. 

The method Promise.withResolvers is not yet supported by Node if you try to run it on the server side - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#browser_compatibility

**Comment by Welchen** [comment]
> Small investigation from my side: I've tested it on Node v20.11.1. The issue does not occur with pdfjs-dist v4.0.379. It only happens in v4.1.392, and I think this started after the changes made in #17854.
> 
> The method Promise.withResolvers is not yet supported by Node if you try to run it on the server side - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#browser_compatibility

Updated my post to include my node version.  Using 20.12.2 (updated today after the issue started) and still seeing the issue as well.  

I have not tried a non-LTS version.  

When we revert back to v4.0.379 we also do not see the issue.   

Looks like we are both seeing the same thing.

**Comment by Snuffleupagus** [comment]
Please use the `legacy`-build, note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by tamuratak** [comment]
This issue seems related to TypeScript files under `types/src/` bundled with `pdfjs-dist`. We can see `PromiseWithResolvers` at `types/src/display/api.d.ts`

- https://cdn.jsdelivr.net/npm/pdfjs-dist@4.1.392/types/src/display/api.d.ts

The `PromiseWithResolvers` is a recently added type:

- https://github.com/microsoft/TypeScript/blob/main/src/lib/esnext.promise.d.ts

Users must set `"target": "ESNext"` in their `tsconfig.json` to compile their project without errors.

A workaround on the users' side is to set `"skipLibCheck": true` in their `tsconfig.json`.

A fix on PDF.js' side would be to set `"target": "ES2020"` instead of `ESNext` in `tsconfig.json`. Then, the usage of `PromiseWithResolvers` can be avoided in the generated type files.

- https://github.com/mozilla/pdf.js/blob/e78ce74b5fd067c563354e6c118379cb4a926d09/tsconfig.json#L3

**Comment by acurrieclark** [comment]
While possibly not a long term fix with other potential breaking changes coming for node, there is a polyfill available for `Promise.withResolvers()` as part of [core-js](https://github.com/zloirock/core-js?tab=readme-ov-file#promisewithresolvers) which is working nicely for me.
