### ISSUE TITLE
dict.get is not a function

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#7303]
There is a problem rendering this PDF: 
[ws_protectyourwork_e.pdf](https://github.com/mozilla/pdf.js/files/254710/ws_protectyourwork_e.pdf)

Using the standard web viewer example (build/generic/web/viewer.html) it runs into an exception, showing the error:

PDF.js v1.5.232 (build: a682cce)
Message: dict.get is not a function

![screen shot 2016-05-09 at 11 06 41](https://cloud.githubusercontent.com/assets/786238/15110018/5d79efa6-15d6-11e6-851f-d81ac6fa95ad.png)

This happens in Chrome, Firefox, Safari on the Mac - haven't tried any others. Message on Safari is: dict.get is not a function. (In 'dict.get('Filter')', 'dict.get' is undefined)

I hope this helps. Not sure if there is a problem with the PDF but I guess it would ideally catch the error anyway. PDF seems to display OK in other software.

Thanks,

Dan

**Comment by Snuffleupagus** [comment]
This is a unfortunately a regression from PR #5910.

It seems to me that we need a **much** more robust way of trying to recover valid `XRef` data from concatenated PDF files, rather than only using a simple condition[1]. (I'm actually a little bit surprised that this hasn't caused more issue in practice.)

---
[1] https://github.com/mozilla/pdf.js/blob/d5c000850aeee9ce19b732d3c09d8d5fe596c98d/src/core/obj.js#L928

**Comment by yurydelendik** [comment]
> rather than just relying on a simple condition

@Snuffleupagus does it miss generation check? or shall we track the latest obj with specific number instead of first?

**Comment by yurydelendik** [comment]
>  PDF seems to display OK in other software.

Adobe Reader asking to re-save the opened PDF, this means PDF was corrupted and the Reader recovered it.

**Comment by Snuffleupagus** [comment]
> does it miss generation check?

I don't think so, since off the top of my head all entries have `gen === 0`.
The problem here is that the PDF file is actually *two* separate PDF files placed in just *one* file, i.e. a completely busted PDF file (in the eyes of the specification).

> or shall we track the latest obj with specific number instead of first?

I'm not sure how we can solve this in general, since in this case there are e.g. two *distinct* `76 0 obj` entires, one from the "first" file and one from the "second one.

**Comment by yurydelendik** [comment]
Best solution will be to determine what the Reader does, I guess. However we need to understand how the file was created and intent of the generator. @danlester  can you provide history of the PDF?

**Comment by yurydelendik** [comment]
> I'm not sure how we can solve this in general, since in this case there are e.g. two distinct 76 0 obj entires, one from the "first" file and one from the "second one.

We shall take the one that is place before the trailer that had catalog object reference. This means we shall not commit to found objects until next trailer is found (if not found it at all we just use what we found)

**Comment by danlester** [comment]
Sorry I missed your notification. I'm afraid I don't know much about the PDF history anyway - it wasn't my file originally. Will see if I can find anything out, but probably not.
