### ISSUE TITLE
pdf.js crashes with "Message: undefined is not a function" during load of bitonal graphics PDF

### ISSUE THREAD

**Issue by GallusMax** [mozilla/pdf.js#5825]
Version Info PDF.js v0.8.1136 (build: ca612e5)

Happens during loading of multipage .pdf with bitonal graphics. 
Just try this link to an .pdf in an owncloud installation:
https://cloud.hsu-hh.de/owncloud/public.php?service=files&t=cea47c3bfa4d07dcce53b2b5c3a1a6b8

**Comment by yurydelendik** [comment]
v0.8.1136 is old version. Can you report it to owncloud?

Works fine in 1.0.1185. Closing as resolved.

**Comment by yurydelendik** [comment]
per https://github.com/owncloud/files_pdfviewer/commits/master/vendor/pdfjs/build/pdf.js, owncloud was recently updated to 1.0.712. See also https://github.com/owncloud/files_pdfviewer/pull/29
