### PR TITLE
Provide a stub for `setAttribute` in order to use the SVG back-end with Node.js

### LINKED ISSUE #8902: error running node pdf2svg.js
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: node
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 23cbe294d578085c295e700963c092816b5bf7e3
- Is an extension: no

Steps to reproduce the problem:
1.  cd examples/node
2. node pdf2svg.js

What is the expected behavior? (add screenshot)
convert pdf to svg

What went wrong? (add screenshot)
```
Error: TypeError: svg.setAttribute is not a function
```

### PR DESCRIPTION
**Pull request by timvandermeij**
This patch fixes a regression from PR #8691 where we switched to using `setAttribute` instead of `setAttributeNS` if no namespace is provided.

To avoid further issues, a stub for `getAttribute` is also created.

Fixes #8902.

### CODE REVIEW

**Review by yurydelendik — APPROVED** [review]
Thank you for the patch.
