### ISSUE TITLE
pdfjs-lib worker not working on safari mac and ios mobiles

### ISSUE THREAD

**Issue by madhuracharya** [mozilla/pdf.js#12769]
Attach (recommended) or Link to PDF file here: "https://edumeister-pdf.s3-us-west-1.amazonaws.com/study%2Bguide.pdf"

Configuration:
- Web browser and its version: Safari Version 13.0.5 (15608.5.11)
- Operating system and its version: Mac OS, 10.15.3 (19D76) Catalina
- PDF.js version: "^2.3.200"
- Is a browser extension: No

Steps to reproduce the problem:
1. clone repo https://github.com/mozilla/pdf.js.git
2. generate generic build with `gulp generic`
2. Use `create-next-app` to create a Next.js app.
3. include `pdf.js` and `pdf.worker.js` in `/public/pdf` directory from previous build.
4. add `<script src="pdf/pdf.js"></script>` tag in `_document.js` 
5. Inside the component, access pdfjsLib using `const pdfjsLib= window.pdfjsLib;`
6. Setup webworker using `pdfjsLib.GlobalWorkerOptions.workerSrc = '/pdf/pdf.worker.js';`
7. render PDF using `pdfjsLib.getDocument(props.url).promise`
7. run `npm run dev`
8. open [localhost:3000](https://localhost:3000)

What is the expected behavior? (add screenshot) 
[expected behaviour](http://res.cloudinary.com/marmin-seller-logo/image/upload/v1608633414/user_billing_logo/jlyn1fnbndajk2zcklud.png)
The browser should be able to access the global variable `pdfjsLib` and render the PDF.

What went wrong? (add screenshot)
[Current output](http://res.cloudinary.com/marmin-seller-logo/image/upload/v1608634461/user_billing_logo/ymsch1zlgnjwtf3qwzmh.png)

The browser is unable to access the variable `pdfjsLib` from `pdf.js`. The exact code runs perfectly fine on chrome and firefox. The error is shown on safari: `SyntaxError: Unexpected token '.'
(anonymous function) — pdf.js:2397`

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: "^2.3.200"

First of all, that version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Use `create-next-app` to create a Next.js app.

That example was removed, for a variety of reasons; please find additional details in https://github.com/mozilla/pdf.js/pull/11864#issue-412082929

> The exact code runs perfectly fine on chrome and firefox. The error is shown on safari: `SyntaxError: Unexpected token '.' (anonymous function) — pdf.js:2397`

That clearly suggests a bug in Safari, rather than in the PDF.js library itself; as such this unfortunately doesn't really seem like an actionable PDF.js issue.
The only advice that we can give is to make sure that you use a `es5`-build of PDF.js library, since those are transpiled and include a number of polyfills.

---

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by madhuracharya** [comment]
Thanks for responding.

I am sorry but, there has been a mistake in the version number that I had previously mentioned. The actual version used is "2.5.207".
It was added accidentally because I was experimenting with a lot of different versions and methods, and I kinda got confused. Again, sorry about that.

But, nothing seemed to work for me on Next.js. They all worked with a plain react project.

Here is a log of everything I tried.

**Attempt 1)** latest version of pdfjs-dist `2.5.207`
    `import pdfjsLib from 'pdfjs-dist/webpack';`
    this caused an error (This happened on all browsers.)

> error - ./node_modules/webpack/lib/node/NodeTargetPlugin.js:11:0
> Module not found: Can't resolve 'module'
    

**Appempt 2)** latest version of pdfjs-dist `2.5.207`
    `import pdfjsLib from 'pdfjs-dist';`
    pdfjsLib is `undefined` (all browsers).
    
**Attempt 3)** I looked into pdfjs-dist/webpack.js and found
      `var pdfjs = require("./build/pdf.js");`
      So i tried to import pdfjs like so
      `import pdfjs from 'pdfjs-dist/webpack';`
       and
     `import pdfjs from 'pdfjs-dist/build/pdf.js';`
       and 
      `import * as pdfjs from 'pdfjs-dist';`

pdfjs is `undefined` in the first 2 ways. The third way didn't throw any errors but it didn't render any PDFs as well.  It said "setting up fake worker" and that's it (all browsers).

      
**Attempt 4)** Found stack overflow page with a potential solution. [Here](https://stackoverflow.com/questions/63553008/looking-for-help-to-make-npm-pdfjs-dist-work-with-webpack-and-django)
    Someone mentioned that upgrading pdfjs-dist to  `v2.6.347` fixed it. So I tried it.
    installed version `2.6.347`
    `import pdfjsLib from 'pdfjs-dist/webpack';`
    I got the error
    

> Error: Cannot find module 'worker-loader?esModule=false!./build/pdf.worker.js' 

**Attempt 5)** Tried using the CDN. [From here](https://cdnjs.com/libraries/pdf.js)
    I used `pdfjs.min.js `and `pdf.worker.min.js`
    It worked on chrome and firefox but broke on safari for some reason saying that there was a syntax error somewhere in 
    pdf.js. 
    

> SyntaxError: Unexpected token '.' (anonymous function) — pdf.js:2397

**Attempt 6)** Tried using ES5 build (latest version).
    I cloned repo [https://github.com/mozilla/pdf.js.git](https://github.com/mozilla/pdf.js.git)
    generated generic build with gulp generic. 
    used babel with `@babel/preset-env` to generate a build.
    included pdf.js and pdf.worker.js into my project.
    When I ran it, got the same error as before in safari. Worked on chrome and firefox.
    

> SyntaxError: Unexpected token '.' (anonymous function) — pdf.js:2397
    
  
**Attempt 7)** Finally I switched back to version `2.3.200` then did something like this.
     Added `?esModule=false` while importing worker.
`import pdfjsLib from "pdfjs-dist/build/pdf.js";`
`import PdfjsWorker from "worker-loader?esModule=false!pdfjs-dist/build/pdf.worker.js";`
`if(typeof window !== 'undefined' && 'Worker' in window) 
{
	pdfjsLib.GlobalWorkerOptions.workerPort = new PdfjsWorker();
}`

This seems to work fine on chrome, firefox and safari. I haven't tested it on iPhone yet (cause i don't have one). 
 I tried the same syntax on the newer versions but I got errors like this
 

> Error: Cannot find module 'worker-loader?esModule=false!./build/pdf.worker.js'

For some reason this syntax only works with version 2.3.200. I don't understand why I have to do all this just to get a simple PDF rendering.


Anyways, I didn't mention this before because I didn't really keep track of all the errors the first time I tried these. I had to re-do them and note down the results. Even though the last workaround worked, I don't know how it is going to behave on mobile and tablets. So, I cannot yet use this in production yet.

**Comment by Snuffleupagus** [comment]
> But, nothing seemed to work for me on Next.js. They all worked with a plain react project.

Unfortunately, I don't believe that any of the PDF.js contributors know either React or Next.js enough to provide any detailed assistance here.

> Here is a log of everything I tried.
> [...]

Unfortunately, this isn't all that helpful since it's *very* difficult for anyone to reproduce *exactly* what you did; hence why we always ask for *runnable examples* rather than code-snippets (please note the last paragraph in https://github.com/mozilla/pdf.js/issues/12769#issuecomment-749493003).

> Tried using ES5 build (latest version).
> I cloned repo https://github.com/mozilla/pdf.js.git
> generated generic build with gulp generic.

This doesn't look entirely correct, since that `gulp` command won't create the `es5`-build.
What you *actually* need to do, if building manually rather than just downloading a release, is to run `gulp generic-es5` instead.

**Comment by madhuracharya** [comment]
I used bable to generate the ES5 build from the gulp one.

I will try to provide you with run-able examples.

**Comment by Snuffleupagus** [comment]
> I used babel to generate the ES5 build from the gulp one.

As clearly mentioned https://github.com/mozilla/pdf.js/issues/12769#issuecomment-750159876: That's wrong and you *must* use `gulp generic-es5`, since otherwise you're not guaranteed that all the necessary polyfills are included.

**Comment by madhuracharya** [comment]
Here is an example that i've created on codesandbox.
[Example1](https://codesandbox.io/s/optimistic-visvesvaraya-rwdjx?file=/pages/index.js)

I am using the latest stable version and I am trying to import pdfjsLib like this
`import pdfjsLib from "pdfjs-dist/webpack";` 
I also tried importing it like so
`import pdfjsLib from "pdfjs-dist/build/pdf";`
Still no luck.

**Comment by Snuffleupagus** [comment]
> I also tried importing it like so
> `import pdfjsLib from "pdfjs-dist/build/pdf";`

And that will not work, since *once again* you *need* to use `es5`-builds for the browsers in question here; hence this should look something like `import pdfjsLib from "pdfjs-dist/es5/build/pdf.js";` instead.

**Comment by madhuracharya** [comment]
There is no `es5` folder inside `pdfjs-dist/` Could you tell me where to find it?

**Comment by Snuffleupagus** [comment]
> There is no `es5` folder inside `pdfjs-dist/` Could you tell me where to find it?

Yes there is, see https://github.com/mozilla/pdfjs-dist/tree/master/es5
However, you'll need to update to a *supported* PDF.js version as mentioned at the top of my very first comment; see https://github.com/mozilla/pdf.js/issues/12769#issuecomment-749493003

**Comment by madhuracharya** [comment]
I feel kinda stupid asking this but, I installed it through npm and I didn't see any es5 folder in node_modules/pdfjs-dist. I'm guessing I need to make a separate build from the repo to use it. 
Is there a way for me to use it directly from the npm node module?

**Comment by Snuffleupagus** [comment]
> I installed it through npm and I didn't see any es5 folder in node_modules/pdfjs-dist.

This would suggest that you didn't actually install either the `latest` or `next` version of the package, which are the only ones that are supported, since those *should* contain the necessary `es5`-directory.

**Comment by madhuracharya** [comment]
> > I installed it through npm and I didn't see any es5 folder in node_modules/pdfjs-dist.
> 
> This would suggest that you didn't actually install either the `latest` or `next` version of the package, which are the only ones that are supported, since those _should_ contain the necessary `es5`-directory.

If you check the codesandbox example that I had provided previously [#12769 (see comment)](https://github.com/mozilla/pdf.js/issues/12769#issuecomment-751364943) , you will be able to see that I am using the latest stable version `2.5.207`. I also tried the next version. Still no luck.

**Comment by Snuffleupagus** [comment]
As previously mentioned, the core PDF.js contributors don't know much (if anything) about either React or Next.js and as such it's unfortunately not really possible for us to provide much assistance with those kind of frameworks.

**Comment by madhuracharya** [comment]
Understandable. Thanks anyways. 
I will continue to use my workaround until someone figures out a better solution.
